Keithley2450:
  adapter: USB0::0x05E6::0x2460::04098155::INSTR
  name: Keithley 2450
  IDN: KEITHLEY
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.keithley.Keithley2450
Keithley2460:
  adapter: USB0::0x05E6::0x2460::04098155::INSTR
  name: Keithley 2460
  IDN: KEITHLEY
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.keithley.Keithley2460
Bentham:
  adapter: COM6
  name: Bentham TLS120Xe
  IDN: USB\VID_04D8&PID_1705\41839/1
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.bentham.Bentham
  kwargs:
    manufacturer: Bentham
    vendor_id: 1240
    read_termination: \r\n\x00
    write_termination: \r\n\x00
TENMANEG:
  adapter: COM3
  IDN: TENMA 72-2715 V6.6 SN:37793902
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.tenma.TENMA
TENMAPOS:
  adapter: COM4
  IDN: TENMA 72-2715 V6.6 SN:37793916
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.tenma.TENMA
TENMALASER:
  adapter: COM7
  IDN: TENMA 72-2715 V6.6 SN:37793899
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.tenma.TENMA
ThorlabsPM100USB:
  adapter: USB0::0x1313::0x8078::P0037982::INSTR
  IDN: Thorlabs,PM100D,P0037982,2.8.1
  target:
    _target_: hydra.utils.get_class
    path: pymeasure.instruments.thorlabs.ThorlabsPM100USB
SerialSensor:
  adapter: COM4
  IDN: ROSATECH,TSN100,P0000003,1.0.1-1
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.serial.SerialSensor
PT100SerialSensor:
  adapter: COM8
  IDN: ROSATECH,TSN100,P0000002,1.0.1
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.serial.PT100SerialSensor
Clicker:
  adapter: COM8
  IDN: ROSATECH,CLK100,P0000003,1.0.0
  target:
    _target_: hydra.utils.get_class
    path: laser_setup.instruments.serial.Clicker
