# Override parameter defaults and Procedure instance attributes here.
# Make sure that key names match the type(procedure).__name__ attribute.

DischargeCC:
  name: CC discharge
  parameters:
    procedure_version:
      value: 1.0.0

_types:
  Wait: ${class:laser_setup.procedures.Wait}
  DischargeCC: ${class:laser_setup.procedures.cell.DischargeCC}
  FakeProcedure: ${class:laser_setup.procedures.FakeProcedure.FakeProcedure}
