# Sequence: list of Procedures to run sequentially. Procedures must be defined in procedures.yaml.
# Otherwise, a reference to the procedure class must be given.


DestroyCell:
  name: Destroy the cell
  description: Destroys the cell by doing heavy cycles
  common_procedure: ${class:laser_setup.procedures.cell.CellProcedure}
  inputs_ignored: ['show_more', 'skip_startup', 'skip_shutdown']
  procedures:
  - DischargeCC
  - DischargeCC
  - DischargeCC

_types:
  DestroyCell: ${sequence:DestroyCell}
